name: Build and Publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        uses: Borales/actions-yarn@1.1.0
        with:
          args: install

      - name: Build
        uses: Borales/actions-yarn@1.1.0
        with:
          args: build

      - name: Publish
        uses: mikeal/merge-release@2.2.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
