name: Pull Requests
on: pull_request
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: npm or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
